version: "3"
services: 
  examples-idp:
    image: ndidplatform/examples:latest
    environment:
        - SERVER_PORT=${EXAMPLE_PORT:-8000}
        - API_SERVER_ADDRESS=http://api-idp:${API_PORT:-8080}
        - NDID_API_CALLBACK_IP=examples-idp
        - NDID_API_CALLBACK_PORT=${EXAMPLE_CALLBACK_PORT:-5000}
    command: idp
    ports:
      - "8000:${EXAMPLE_PORT:-8000}"
    networks:
      - ndidplatform
  examples-rp:
    image: ndidplatform/examples:latest
    environment:
        - SERVER_PORT=${EXAMPLE_PORT:-8000}
        - API_SERVER_ADDRESS=http://api-rp:${API_PORT:-8080}
        - NDID_API_CALLBACK_IP=examples-rp
        - NDID_API_CALLBACK_PORT=${EXAMPLE_CALLBACK_PORT:-5000}
    command: rp
    ports:
      - "8001:${EXAMPLE_PORT:-8000}"
    networks:
      - ndidplatform
  examples-as:
    image: ndidplatform/examples:latest
    environment:
        - SERVER_PORT=${EXAMPLE_PORT:-8000}
        - API_SERVER_ADDRESS=http://api-as:${API_PORT:-8080}
        - NDID_API_CALLBACK_IP=examples-as
        - NDID_API_CALLBACK_PORT=${EXAMPLE_CALLBACK_PORT:-5000}
    command: as
    ports:
      - "8002:${EXAMPLE_PORT:-8000}"
    networks:
      - ndidplatform
networks:
  ndidplatform:
